name: learn-github-actions
run-name: ${{ github.actor }} Running Demo Application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ß
        with:
          java-version: '20'
      - run: mvn package