name: learn-github-actions
run-name: ${{ github.actor }} Running Demo Application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run setup-java with the cache for maven
        uses: ./.github/workflows/ß
        with:
          java-version: '20'
        run: mvn package